### ISSUE TITLE
Missing In Checksum Error

### ISSUE THREAD

**Issue by tlynx538** [LinuxForExynos/pmos-samsung-on7xelte#18]
Hello,
 I followed the instructions mentioned on the README. And this is the output i received when pmbootstrap install --android-recovery-zip
```
ubuntu@ubuntu:~/pmos-samsung-on7xelte$ pmbootstrap log
Executing busybox-1.35.0-r27.trigger
Executing fontconfig-2.14.1-r0.trigger
Executing mkfontscale-1.2.2-r1.trigger
OK: 613 MiB in 156 packages
(019474) [07:41:22] (native) calculate depends of ccache-cross-symlinks, gcc-aarch64, g++-aarch64 (pmbootstrap -v for details)
(019474) [07:41:22] (native) install ccache-cross-symlinks gcc-aarch64 g++-aarch64
(019474) [07:41:22] % sudo rm -f /home/ubuntu/.local/var/pmbootstrap/chroot_native/tmp/apk_progress_fifo
(019474) [07:41:22] % sudo mkfifo /home/ubuntu/.local/var/pmbootstrap/chroot_native/tmp/apk_progress_fifo
(019474) [07:41:22] (native) % cat /tmp/apk_progress_fifo
(019474) [07:41:22] (native) % sh -c exec 3>/tmp/apk_progress_fifo; apk --no-progress --progress-fd 3 add ccache-cross-symlinks gcc-aarch64 g++-aarch64
(019474) [07:41:22] New background process: pid=20394, output=background
WARNING: Ignoring /mnt/pmbootstrap-packages: No such file or directory
OK: 613 MiB in 156 packages
(019474) [07:41:22] (native) build aarch64/linux-samsung-on7xelte-3.18.140-r0.apk
(019474) [07:41:22] (native) % rm -rf /home/pmos/build
(019474) [07:41:22] % sudo cp -rL /home/ubuntu/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-samsung-on7xelte/ /home/ubuntu/.local/var/pmbootstrap/chroot_native/home/pmos/build
(019474) [07:41:22] (native) % chown -R pmos:pmos /home/pmos/build
(019474) [07:41:22] % sudo umount /home/ubuntu/.local/var/pmbootstrap/chroot_native/mnt/pmaports
(019474) [07:41:22] % sudo mount --bind /home/ubuntu/.local/var/pmbootstrap/cache_git/pmaports /home/ubuntu/.local/var/pmbootstrap/chroot_native/mnt/pmaports
(019474) [07:41:22] (native) % busybox su pmos -c HOME=/home/pmos mkdir -p /home/pmos/build
(019474) [07:41:22] (native) % busybox su pmos -c HOME=/home/pmos ln -sf /mnt/pmaports/.git /home/pmos/build/.git
(019474) [07:41:22] (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc HOME=/home/pmos abuild -D postmarketOS -d
>>> linux-samsung-on7xelte: Building pmos/linux-samsung-on7xelte 3.18.140-r0 (using abuild 3.10.0_rc1-r2) started Mon, 31 Oct 2022 07:41:22 +0000
>>> linux-samsung-on7xelte: Checking sanity of /home/pmos/build/APKBUILD...
>>> ERROR: linux-samsung-on7xelte: linux-samsung-on7xelte-dd714bdebd1ab9dcf2f9482d8565c688c106114c.tar.gz is missing in checksums
(019474) [07:41:23] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(019474) [07:41:23] NOTE: The failed command's output is above the ^^^ line in the log file: /home/ubuntu/.local/var/pmbootstrap/log.txt
(019474) [07:41:23] ERROR: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc HOME=/home/pmos abuild -D postmarketOS -d
(019474) [07:41:23] See also: <https://postmarketos.org/troubleshooting>
(019474) [07:41:23] Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/__init__.py", line 49, in main
    getattr(frontend, args.action)(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/helpers/frontend.py", line 324, in install
    pmb.install.install(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/install/_install.py", line 1046, in install
    create_device_rootfs(args, step, steps)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/install/_install.py", line 982, in create_device_rootfs
    pmb.build.package(args, pkgname, args.deviceinfo["arch"])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/build/_package.py", line 523, in package
    if not init_buildenv(args, apkbuild, arch, strict, force, cross, suffix,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/build/_package.py", line 207, in init_buildenv
    depends, built = build_depends(args, apkbuild, depends_arch, strict)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/build/_package.py", line 155, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/build/_package.py", line 528, in package
    (output, cmd, env) = run_abuild(args, apkbuild, arch, strict, force, cross,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/build/_package.py", line 455, in run_abuild
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build", env=env)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/chroot/user.py", line 26, in user
    return pmb.chroot.root(args, cmd, suffix, working_dir, output,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/chroot/root.py", line 83, in root
    return pmb.helpers.run_core.core(args, msg, cmd_sudo, None, output,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/helpers/run_core.py", line 351, in core
    check_return_code(args, code, log_message)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pmb/helpers/run_core.py", line 221, in check_return_code
    raise RuntimeError(f"Command failed (exit code {str(code)}): " +
RuntimeError: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc HOME=/home/pmos abuild -D postmarketOS -d
```
How can it be fixed?

**Comment by Otus9051** [comment]
Have you done `pmbootstrap checksum samsung-on7xelte` before building?

My bad, I forgot to include this step in the readme. But this tree was build thinking that the user has indeed read the PostMarketOS Porting guide beforehand.

**Comment by tlynx538** [comment]
Oh i did not see this instruction in the README. However, `pmbootstrap checksum samsung-on7xelte` worked precisely. Now i am getting the following:
```
>>> linux-samsung-on7xelte: Unpacking /var/cache/distfiles/linux-samsung-on7xelte-dd714bdebd1ab9dcf2f9482d8565c688c106114c.tar.gz...
>>> ERROR: linux-samsung-on7xelte: Is $builddir set correctly?
>>> ERROR: linux-samsung-on7xelte: prepare failed
```
I think the Build dir should be set correctly in APKBUILD file.

**Comment by Otus9051** [comment]
This should not be happening. Let me check myself.

**Comment by tlynx538** [comment]
Is there any update on this?

**Comment by Otus9051** [comment]
Try `pmbootstrap checksum linux-samsung-on7xelte` maybe
No idea what is happening on your side... But I can build it without any problem...

**Comment by tlynx538** [comment]
Yeah i tried with all these:
```
pmbootstrap checksum linux-samsung-on7xelte
pmbootstrap checksum device-samsung-on7xelte
pmbootstrap checksum firmware-samsung-on7xelte
```
I had used Ubuntu Server 20.04 VM on VMWare Fusion for building, i shall now try with fedora and see if it works.
Thanks for the update :)
